version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - whisper_cache:/root/.cache/whisper
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4G
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --maxclients 10000 --maxmemory 2gb
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  redis_data:
  whisper_cache:
